# Generated by Django 5.2.6 on 2025-10-27 12:29

import django.db.models.deletion
import front.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=front.models.generate_token, max_length=128, verbose_name='Token')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.IntegerField(unique=True, verbose_name='Registration number')),
                ('reg_date', models.BigIntegerField(default=1761568180, verbose_name='Registration date')),
                ('open_access', models.BooleanField(default=False, verbose_name='Open access')),
                ('fz_53', models.BooleanField(default=False, verbose_name='59-FZ')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('finished', 'finished')], max_length=20, verbose_name='Status')),
                ('category', models.CharField(choices=[('complaint', 'complaint'), ('suggestion', 'suggestion'), ('information_request', 'information_request'), ('gratitude', 'gratitude'), ('other', 'other')], max_length=30, verbose_name='Category')),
                ('subcategory', models.CharField(choices=[('transport', 'transport'), ('housing_utilities', 'housing_utilities'), ('roads', 'roads'), ('public_services', 'public_services'), ('safety', 'safety'), ('urban_environment', 'urban_environment'), ('transport', 'transport'), ('digital_services', 'digital_services'), ('ecology', 'ecology'), ('culture_sport', 'culture_sport'), ('schedule', 'schedule'), ('documents', 'documents'), ('contacts', 'contacts'), ('procedures', 'procedures'), ('public_services', 'public_services'), ('individual_employee', 'individual_employee'), ('community', 'community'), ('unclassified', 'unclassified'), ('multiple_topics', 'multiple_topics')], max_length=30, verbose_name='Subcategory')),
                ('fact', models.TextField(verbose_name='Fact')),
                ('organisation', models.CharField(max_length=300, verbose_name='Organisation')),
                ('filling_date', models.BigIntegerField(default=1761568180, verbose_name='Filling date')),
                ('fast_track', models.BooleanField(default=False, verbose_name='Fast track')),
                ('first_name', models.CharField(max_length=200, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last name')),
                ('birth_date', models.BigIntegerField(verbose_name='Birth date')),
                ('address', models.TextField(max_length=200, verbose_name='Address')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone')),
                ('question', models.TextField(verbose_name='Question')),
                ('region', models.TextField(verbose_name='Region')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='front.system', verbose_name='System')),
            ],
        ),
    ]
