# Generated by Django 5.2.6 on 2025-10-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0aW1lIjoxNzYwNDQ2NjA1LjQ0NzMxNjZ9.1sFhQR1yjPz5qq3IR3d-FAQOQquwh8PvflGWniaCs44', max_length=128, verbose_name='Token')),
                ('comment', models.TextField(null=True, verbose_name='Comment')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='front.user', verbose_name='User')),
            ],
        ),
    ]
